# Done to increase the memory available to Gradle.
	org.gradle.jvmargs=-Xmx1G
	org.gradle.parallel=true

# Minecraft Version Properties
	minecraft_version=1.21.6

# Fabric Properties
	yarn_mappings=1.21.6+build.1
	fabric_version=0.127.0+1.21.6
	loader_version=0.16.14

# Mod Properties
	archives_base_name = DaylightChangerStruggle
	maven_group = jugglestruggle.timechanger
	mod_version = 0.0.2