# Increase the memory available to Gradle.
	org.gradle.jvmargs=-Xmx4G
	org.gradle.parallel=true

# Minecraft Version Properties
	minecraft_version=26.1

# Fabric Properties
	loader_version=0.18.4
	fabric_version=0.144.0+26.1
	yarn_mappings=26.1+build.1
	loom_version=1.15-SNAPSHOT

# Mod Properties
	archives_base_name = DaylightChangerStruggle
	maven_group = jugglestruggle.timechanger
	mod_version = 0.0.4
