# Increase the memory available to Gradle.
	org.gradle.jvmargs=-Xmx4G
	org.gradle.parallel=true

# Minecraft Version Properties
	minecraft_version=26.3

# Fabric Properties
	loader_version=0.19.5
	fabric_version=0.159.4+26.3
	yarn_mappings=26.3+build.1
	loom_version=1.17-SNAPSHOT

# Mod Properties
	archives_base_name = DaylightChangerStruggle
	maven_group = jugglestruggle.timechanger
	mod_version = 0.0.5
